language: ruby

rvm:
- 2.5

sudo: required

services: docker

env:
  global:  
  - COMMIT=${TRAVIS_COMMIT::8}

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script:  bash .travis/deploy.sh
  on:
    branch: master
