language: ruby

rvm:
- 2.5

sudo: required

services: docker

env:
  global:
  - secure: "qNId/4WLaqBBGG84Su1g12YH0biEdIWVQcvdZSvg9+o8WgiR2QyhGvJ1am+NOy1EFopdwD7OTC0JN90zbHBgix5J+as8bYwZ60TmkdEmW+TP/WV5cKIqUO+pfJm4G/IiDV8HGXQD7dLdG9s29R3z7dJci1lAlJdNpV0o45Kgr6SYxp9ps5jwZvh41o77lrX42zCDopw3VddAcjLmZPkp1bzigxTwJDS9SHi/E5diVzDtqa0A/ph2sD/ezTzcMjMnreBclJrjy2U0Kyu21OAD0Gcw8/5ZARGYeIJPKd7ZDLMX5udc9wE/b2AEqA9JND6Vxh8KbGCXRVDtay290zdYwMrAw4ahOsR+p4yPZiPzERjnAw7U42WwIDuHTIMFpIZ03/MfelYHOn16/0j5b/FjXAuRs94Vi4zyQEUnKZC7b5u+0kjU8T4esPW7iOuHdJy9e4gjJW1wNIsCH4KTljwSdIgOPnCeJEmCwKJbHpMN4HIEqM+BZkyuOUw+xU5Nqo3eNyOOazthG0Bsax3RHJXbrB+IOpiiC6ulai/oQ4KkmDJohnC6ge6sxP0yDWRfPtYCNsHP71QxhtNMFpVnZJowoqzN3TCBiLS8febPcDlXqpVgeaYcqMPMebKqprhtHvwSyn653//8ZepcPr3ToAYZMRQv1mLiKRaRlquTQX1NlTk=
  - secure: e6ObVuztcm2wiCsoVJ0gtUDNqYQqYgVC2VbW0FJWz/r2n3uHqREr48efKvP56gcwpWqewJMxLAu8us89aPNX0ZEgTL9NV9p1rB4qD5Yex6uki4TjPcoj8d56O/lvuJ2fMSjSEzcnY0H61XhVWGWNX+OpDeIgKDFrfYyDYzhb0uGKiUZ/xTgyBe5yymKr82SKaOVpL9PPL0ZIOQ6UT1YqsatUn/EfUytanHn9LtpsxvcAgf0+xJuQoAuvD2TUGStToP4g8vW6kXHZmUm8atvod+BY1ZMxLbU88HwsH6O2sBMGXJVXk99cQ7CcvOv74BE+V74k6k9FrdAOKsCnvkRkvneVojtnv8pQaXT5L4wWJOHCPv00hm4f7uATdGPExWdRzXBsbj05OJBGJ2qdDZ5FXJ/sQyHgvPhttjX9fSITcdY9XAqiO/GMfCWlJ4Sg2bGemy0RvecE8Pye2cfRecHF27X/iLCsg4FsHzOEikS2dLANkZVUrT6m5iaGEU1mmXidyZDVxIIHn9xGIlmbLimcHg5uYy64CGNixRqO0+rfJj1sAZRikXkJZE0YYP8wFqhQM8BTzMfeIXZP4qosxB+djI2QinUx6t1yHFhF/8Vvm+ZnAqExMCydiP6eAn/QYoUUJLvy/OhhSfhVZNcggSn1uv9SGgp6R10rKLctfysV3nA=
  - COMMIT=${TRAVIS_COMMIT::8}

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec


deploy:
  provider: script
  script:  bash .travis/deploy.sh
  on:
    branch: master
