language: ruby

rvm:
- 2.5

sudo: required

services: docker

env:
  global:
  - secure: "gBVELm9M8CwlA9wtgzGSHhD5+A9AsVuymlTxFpm8UI0bHm5CHExrYqwenaqM74SIT9QM8XDDdVi02mqzvNUKJb5eoJA77z1FDmyOyOUk+QmYEWBmxORbJKHU+XaHDs3sWWLah0wwZAZ817ZW8QdviOOTQC5md8K82bCNuEXtriYUZJZneWthpinKFh1TXcJw1YgFpyImDdAh0ToSEH/x+WB+6p1NvB2Vf7lYwjNK9u14W49wWCt/pYeWcwmVVOZYlv9xS90qCKk0xBGuFk4rLz9F09u9Xj/D9qGxL3+sDXYajyyte77pLmKOMy8/MjFlpiqAd/vUl7TjfuAg8RFl67kjjYoxNwn9YhzuYbN+zWEe/QRugxAnBEnqZ6aULul4YrGlLUx0N1SBLl5nGKItaxjlAs1gQAVNK2eb43U2vdBLtEwXAo/XcqNcKVQMENBj8GwMIrihqUt7VOHdk2yeoBf/PbsFxjiF23jijtYjEWz8F8K3ufE/GXziPtKnJlMlED/NHC8qo8YE6IyaiTn9UPFe5ecZwIIzp+OGmmKdpe+oBB6Kz5dRRyiZv11nT+54Jw3uiq0UqUaQLTz6tlc6yIKOhaSHl+cp6EI5E2Azz2jQwNf33fj1eK48Mu43nkcX7HBiDQ8SHlI9k7o06g1fnzEG2f6SouoSgv8nZKlzBSU="
  - secure: "e6ObVuztcm2wiCsoVJ0gtUDNqYQqYgVC2VbW0FJWz/r2n3uHqREr48efKvP56gcwpWqewJMxLAu8us89aPNX0ZEgTL9NV9p1rB4qD5Yex6uki4TjPcoj8d56O/lvuJ2fMSjSEzcnY0H61XhVWGWNX+OpDeIgKDFrfYyDYzhb0uGKiUZ/xTgyBe5yymKr82SKaOVpL9PPL0ZIOQ6UT1YqsatUn/EfUytanHn9LtpsxvcAgf0+xJuQoAuvD2TUGStToP4g8vW6kXHZmUm8atvod+BY1ZMxLbU88HwsH6O2sBMGXJVXk99cQ7CcvOv74BE+V74k6k9FrdAOKsCnvkRkvneVojtnv8pQaXT5L4wWJOHCPv00hm4f7uATdGPExWdRzXBsbj05OJBGJ2qdDZ5FXJ/sQyHgvPhttjX9fSITcdY9XAqiO/GMfCWlJ4Sg2bGemy0RvecE8Pye2cfRecHF27X/iLCsg4FsHzOEikS2dLANkZVUrT6m5iaGEU1mmXidyZDVxIIHn9xGIlmbLimcHg5uYy64CGNixRqO0+rfJj1sAZRikXkJZE0YYP8wFqhQM8BTzMfeIXZP4qosxB+djI2QinUx6t1yHFhF/8Vvm+ZnAqExMCydiP6eAn/QYoUUJLvy/OhhSfhVZNcggSn1uv9SGgp6R10rKLctfysV3nA="  
  - COMMIT=${TRAVIS_COMMIT::8}

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script:  bash .travis/deploy.sh
  on:
    branch: master
