language: ruby

rvm:
- 2.5

sudo: required

services: docker

env:
  global:
  - secure: "oeHBsEt9JrMSwfjoxQmrEB5+8WIx4uLImXhuOHDVYHaMlsXOoWJ4NTTiQCLhoQYulmBub/ip4177vDJ262xd9cHDj7F1jt3tDzBr9BEC5mBY1hwG/Ja6Ugy/l6F+4qz19zO4V9bS+KkJaGPKmXhffSiO6tnObDA45fGHmPPsgCdzUrZqvhMPMq+BViDRwyT8u7+znNNupb2e7Oo4rwnUYzyhMBVhG+jMzf36uHEGB5gkSZdQzRlvOEjAgLLKeFAJMvNN7CnQhMyFDify9x2xmWim4p1YUgl9nPCj5b97wbTLIS+X9cnood0hv/ygj/0PtowBzQbBOY7lqKw+z3aVXsvi6yvNxmdWZrChU4xmeqldFWnSieJ9jEiBhamz1JwZCPbLQuWldNDPZVYNrocslH6qnSfqyJhN2SEiRRykda1B5uqfgIDH+3iYsF40uiYILSz/uTAcrXLknyrsr5vWhPzBHf4ghWkWgVx8/Iicz3ut03ANSmm9frOgbI22pFeevNUSPyT2m1X2wPaFcd6+2tClIQzZClPftLyikZcNYNsINNV/JBGm1VZ1mioh39Ha9diDqqib8jJWXPC0WKRn7qqAvBI4sGKMMKn07juW+5cLoZHC0HcBhJI13LRN5LJkVTO2f8kDyM83rmvXdYjj34MAkl3gZ6hm0WxWPHXd3Ak="  
  - secure: "PaZJPQNpTf499FBPl4vnJzormWgvQLN0q+tFi86govCjDgKe2CzPlocsUebmVbzb7a2ZdN7QljU+n5aw1uwIbPrd6CfP+bc3CwzxabkVnS52fa3Qn/ztrxydKV6Oze+onvrkr/hG+m1lojzdZ44HkNc78AVWqBOV2Vg6owqWTBsepYhzflIe50B9X9El6Dq1QUPT7+ppCXOKeKF8yXSiYHtxuD8S3KqT6nJG/mRFxmAd0fIxlIekCi2E/As4fK2ZRiSiw6i4OyyjItHAVhaXTyHQfoPqNzZ3MHEcfbEh9RThIOJ62YLjq9jY25rDAVeetYBifhTXa0eD/I/wZ1t90Ifx/wihqItb1YuvLBYf2lLbWQajQgXaZcjujDeBzVk9j3hX2hiApILx7i1O6tYLbR7OooclT4Zs/rkYJeCmffTL9PNYPhGsbgGjAXR/iIj0gZwD5HyHfs6BCyv5GlyD3QM7U1+wlZ1pBE06et64VNoM2rzDQ/3ed/ATxL7BR+/JZ+zYx6Dyp8t6wriLHO3STWkkhSsaJiJk92SSe6o5DJC+Be628Sx8ZGUqmHueIeaJaRw9kDXyLGS6EtYW7LWftI6Ief2Grc0zxvMO4k+yoG9JBFo0wtHRVYMAvIK9M8K4T7Dm5KVADau511ucoYVdLFnIG+nGosaoRoz+3qExobg="  
  - COMMIT=${TRAVIS_COMMIT::8}

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  provider: script
  script:  bash .travis/deploy.sh
  on:
    branch: master
